config/urls.py
from django.conf import settings
from django.urls import include, path
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views
from django.shortcuts import redirect,reverse
from http import HTTPStatus


def home_redirect(request):
    """首页重定向"""
    return redirect(reverse('article:list'))

urlpatterns = [
    path("", home_redirect, name="home"),
    path(
        "about/", TemplateView.as_view(template_name="pages/about.html"), name="about"
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    path('markdownx/', include('markdownx.urls')),  # 第三方包markdown路由配置
    path('search/',include('haystack.urls')),
    # User management
    path("circle/", include("segmentfault.apps.circle.urls", namespace="circle")),
    path("users/", include("segmentfault.apps.users.urls", namespace="users")),
    path("article/",include("segmentfault.apps.article.urls",namespace="article")),
    path("qa/",include("segmentfault.apps.qa.urls",namespace="qa")),
    path("accounts/", include("allauth.urls")),
    path("comments/",include("django_comments.urls")),
    path("msg/",include("segmentfault.apps.msg.urls",namespace='msg')),
    path("notice/",include("segmentfault.apps.notice.urls",namespace="notice")),


    # Your stuff: custom urls includes go here
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

def RESPONSE_500(request):
    return HTTPStatus(500)

handler500 = RESPONSE_500

segmentfault/apps/circle/urls.py
# -*- coding:utf-8 -*-
# @Time    : 2019/6/22 8:18 PM
# @Author  : __wutonghe__



from django.urls import path

from segmentfault.apps.circle.views import *
app_name = "circle"
urlpatterns = [
    path("list/", view=CircleList.as_view(), name="list"),
    path("new/",view=new_circle,name="new"),
    path("like/",view=change_like,name="like"),
    path("delete/",view=delete_circle,name='delete'),
    path("getreply/",view=get_reply,name='getreply'),
    path("reply/",view=reply,name='reply'),
    path("test/",view=test,name='test')

]

segmentfault/apps/msg/urls.py
# -*- coding:utf-8 -*-
# @Time    : 2019/7/18 7:55 PM
# @Author  : __wutonghe__


from django.urls import path

from segmentfault.apps.msg.views import *

app_name = "msg"
urlpatterns = [
    path("createdata/",create_data),
    path("allletter/",MessageList.as_view(),name="allletter"),
    path("letter/<str:user_id>",MessageDetail.as_view(),name='letter'),
    path("post-letter/",post_letter,name='post_letter'),

]

segmentfault/apps/notice/urls.py
# -*- coding:utf-8 -*-
# @Time    : 2019/7/18 7:55 PM
# @Author  : __wutonghe__

from django.urls import path

from segmentfault.apps.notice.views import *

app_name = "notice"
urlpatterns = [
    path('all/',AllNoticeList.as_view(),name='all'),
    path('unread/',UnReadNoticeList.as_view(),name='unread'),
    path('light/',notice_light,name='light'),
    path('readall/',mark_read,name='readall'),

]

segmentfault/apps/qa/urls.py
# -*- coding:utf-8 -*-
# @Time    : 2019/7/6 4:03 PM
# @Author  : __wutonghe__


from django.urls import path

from segmentfault.apps.qa.views import *

app_name = "qa"
urlpatterns = [
    # 创建问题
    path("create/",QuestionCreate.as_view(),name='create'),

    #分类查询问题
    path("new/",NewView.as_view(),name='new'),
    # path("subscribed/",Subscribed.as_view(),name='subscribed'),
    path("unanswered/",UnAnswered.as_view(),name='unanswerd'),
    path("hottest/",HotTest.as_view(),name='hottest'),
    # path("pay/",)

    #问题详情
    path("detail/<int:question_id>",QuestionDetail.as_view(),name='detail'),

    #发表回复
    path("reply/<int:question_id>",AnswerCreate.as_view(),name='reply'),

    #up or dowm
    path("vote/",votedquestion,name='votedquestion'),
    path("answer/vote/",votedanswer,name='votedanswer'),
    path("accept/",acceptanswer,name='acceptanswer'),

]

segmentfault/apps/users/urls.py
from django.urls import path

from segmentfault.apps.users.views import (
    user_redirect_view,
    UserDetailView,
    UserUpdateView,
    UserList,
)

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("update/", UserUpdateView.as_view(), name="update"),
    path("userhome/",UserList.as_view(),name='userhome'),
    path("<str:username>/", UserDetailView.as_view(), name="detail"),

]

segmentfault/apps/article/forms.py
from markdownx.fields import MarkdownxFormField
from django import forms
from segmentfault.apps.article.models import Article


class ArticleForm(forms.ModelForm):
    content = MarkdownxFormField()

    class Meta:
        model = Article
        fields = ['title','image','status','content',]

segmentfault/apps/article/views.py
import datetime

from django.shortcuts import render,HttpResponse
from django.views.generic import ListView,UpdateView,CreateView,View,DetailView
from segmentfault.apps.article.forms import *
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.decorators.cache import cache_page
from segmentfault.apps.article.models import Article
from django.contrib.auth.mixins import LoginRequiredMixin
from django_comments.signals import comment_was_posted
from segmentfault.apps.notice.views import post_notice


@method_decorator(cache_page(60*60*24),name='get')  # 缓存
class ArticleCreate(LoginRequiredMixin,CreateView):
    model = 'Article'
    template_name = 'article/article_add.html'
    form_class = ArticleForm

    def form_valid(self, form):
        """
        为文章添加作者
        :param form:
        :return:
        """
        form.instance.user = self.request.user
        return super().form_valid(form)

    def post(self, request, *args, **kwargs):
        return super(ArticleCreate, self).post(request,*args,**kwargs)
    def get_success_url(self):
        return reverse_lazy("article:list")


class ArticleList(ListView):
    """
    文章列表
    """
    model = Article
    template_name = 'article/article_list.html'
    context_object_name = 'article_list'
    paginate_by = 4

    def get_queryset(self):
        article_list = Article.objects.filter(status='1')
        return article_list

    def get_context_data(self, *, object_list=None, **kwargs):
        # 返回最近定义的一段时间内的热门文章
        now = datetime.datetime.now()
        start = now - datetime.timedelta(days=100,hours=23, minutes=59, seconds=59)
        hot_article = self.model.objects.filter(create_time__gt=start).order_by('-click_num')[0:9]
        kwargs['hot_article'] = hot_article
        kwargs['pwd_page'] = 'article'

        return super(ArticleList, self).get_context_data(**kwargs)


class ArticleDetail(DetailView):
    """
    文章详情
    """
    model = Article
    template_name = 'article/article_detail.html'
    context_object_name = 'article'
    pk_url_kwarg = 'article_id'

    def get_object(self, queryset=None):
        obj = super(ArticleDetail, self).get_object()
        obj.click_num += 1  # 增加点击量
        obj.save()
        return obj

    def get_context_data(self, **kwargs):
        kwargs['article_type'] = 'xiangqing'
        return super().get_context_data(**kwargs)


class ArticleUpdate(LoginRequiredMixin,UpdateView):
    """
    更新文章
    """
    model = Article
    template_name = 'article/article_add.html'
    form_class = ArticleForm
    pk_url_kwarg = 'article_id'

    def get_success_url(self):
        #通过get_object()获取对象
        return reverse_lazy('article:detail',args=[self.get_object().id])


class ArticleDrafts(LoginRequiredMixin,ListView):
    """
    草稿箱
    """
    model = Article
    template_name = 'article/drafts.html'
    context_object_name = 'article_list'
    paginate_by = 4
    def get_queryset(self):
        article_list = Article.objects.filter(status='0',user=self.request.user)
        return article_list


def comment_signal(**kwargs):
    """信号函数"""
    sender = kwargs['request'].user
    instance = kwargs['comment'].content_object
    post_notice(sender,instance.user,'R',instance)


# https://django-contrib-comments.readthedocs.io/en/latest/signals.html#comment-was-posted
comment_was_posted.connect(receiver=comment_signal)  # django-comment-signal;

segmentfault/apps/circle/views.py
from django.shortcuts import render
from django.template.loader import render_to_string
from django.http import HttpResponse,JsonResponse
from .models import *
from django.views.generic import ListView
from my_utils.decorator import ajax_login_requird
from django.views.decorators.http import require_http_methods
from segmentfault.apps.notice.views import post_notice

# Create your views here.


class CircleList(ListView):
    '''
    动态列表
    '''
    model = CircleMessage
    paginate_by = 5
    template_name = 'circle/circle_list.html'
    context_object_name = 'circle_list'
    ordering = ('like',)

    def get_queryset(self,**kwargs):
        return CircleMessage.objects.filter(is_comment=False,is_delete=False).select_related('user','parent')

    def get_context_data(self, *, object_list=None, **kwargs):

        kwargs['testob'] = CircleMessage.objects.all().first()
        return super().get_context_data(**kwargs)


@ajax_login_requird
@require_http_methods(["POST"])
def new_circle(request):
    '''
    发布动态接口
    :param request:
    :return:
    '''
    import uuid
    ob = CircleMessage.objects.create(uuid=uuid.uuid4(), user=request.user, context=request.POST.get('message').strip())

    return render(request, 'circle/circle_single.html', {"circle": ob})


@ajax_login_requird
@require_http_methods(["POST"])
def change_like(request):
    '''
    点赞取消赞接口
    :param request:
    :return:
    '''
    uuid = request.POST.get("uuid", '')
    ob = CircleMessage.objects.filter(uuid=uuid).first()
    if ob:
        res = ob.change_like(request.user)
        return JsonResponse({"status": 2000, "message": True, 'like_num': ob.get_like_num()})
    else:
        return JsonResponse({"status": 5000, "message": False})


@ajax_login_requird
@require_http_methods(["POST"])
def delete_circle(request):
    '''
    删除动态或评论接口
    :param request:
    :return:
    '''
    uuid = request.POST.get("uuid", '')
    ob = CircleMessage.objects.filter(uuid=uuid).first()
    ob.is_delete = True
    ob.save()
    return JsonResponse({'status': 2000, 'message': True})


@require_http_methods(["POST"])
def get_reply(request):
    '''
    评论列表接口
    :param request:
    :return:
    '''
    uuid = request.POST.get('uuid','')
    ob = CircleMessage.objects.filter(uuid=uuid).first()
    reply_num = ob.get_comment_num()
    reply_query = ob.get_comment(10)
    context = {
        'reply_list': reply_query,
        'reply_num':reply_num,
        'uuid':ob.uuid,
    }

    html_text = render_to_string("circle/circle_reply.html",context)
    return JsonResponse({"status":2000,"html_text":html_text})


@ajax_login_requird
@require_http_methods(["POST"])
def reply(request):
    '''
    发表回复接口
    :param request:
    :return:
    '''
    uuid = request.POST.get("uuid",'')
    text = request.POST.get('text','').strip()
    parent = CircleMessage.objects.filter(uuid=uuid).first()
    ob = CircleMessage.objects.create(user=request.user,context=text,parent=parent,is_comment=True)
    ob.save()
    post_notice(request.user,parent.user,'R',parent)  # 发送websocket通知
    return JsonResponse({"status":2000})


def test(request):
    from .tasks import app1
    a = app1.delay()
    return HttpResponse('ok')

segmentfault/apps/homepage/views.py
from django.shortcuts import render

# Create your views here.

segmentfault/apps/msg/views.py
from django.shortcuts import render,HttpResponse
from django.template.loader import render_to_string
from django.http.response import JsonResponse
from my_utils.decorator import ajax_login_requird
from django.views.decorators.http import require_http_methods
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView
from segmentfault.apps.msg.models import Message
from segmentfault.apps.users.models import User


class MessageList(LoginRequiredMixin,ListView):
    model = Message
    template_name = 'message/message_privateletter.html'
    context_object_name = "message_list"

    def get_queryset(self):
        """
        返回所有聊天用户
        :return:
        """
        return []

    def get_context_data(self, *, object_list=None, **kwargs):
        """
        获取所有私信对象
        :param object_list:
        :param kwargs:
        :return:
        """
        set1 = self.model.objects.filter(sender=self.request.user).select_related('sender', 'recipient')
        set2 = self.model.objects.filter(recipient=self.request.user).select_related('sender', 'recipient')
        all_private_users = set()
        for vo in set1:
            all_private_users.add(vo.recipient)
        for vo in set2:
            all_private_users.add(vo.sender)
        kwargs['all_users'] = all_private_users  # 获取所有私信对象
        return super().get_context_data(**kwargs)



class MessageDetail(MessageList):
    """
    返回聊天记录
    """
    def get_queryset(self):
        message_list = self.model.objects.get_conversation(self.request.user,self.kwargs['user_id'])

        if not message_list:  # 当第一次发起私信的时候，隐式的创建一个message
            recipient = User.objects.filter(id=self.kwargs['user_id']).first()
            from my_utils.CONSTANT import PRIVATE_FIRST_WORDS  # 初始打招呼语句
            ob = Message.objects.create(sender=self.request.user,recipient=recipient,message=PRIVATE_FIRST_WORDS)
            message_list = [ob]

        return message_list

    def get_context_data(self, *, object_list=None, **kwargs):
        kwargs['recipient'] = int(self.kwargs['user_id'])
        return super().get_context_data(**kwargs)



def create_data(request):
    user = User.objects.get(id=2)
    ob = Message.objects.create(message='byebye',sender=request.user,recipient=user,)
    return HttpResponse('ok')


@ajax_login_requird
@require_http_methods(["POST"])
def post_letter(request):
    recipient = request.POST.get('recipient')
    message = request.POST.get('message')
    if not recipient:
        return JsonResponse({'status':5000,'msg':'请选择一个好友之后再发送'})

    from segmentfault.apps.users.models import User
    r_user = User.objects.filter(id=recipient).first()  # 接收者
    ob = Message.objects.create(sender=request.user,recipient=r_user,message=message)  # 生成新聊天记录
    context = {'message': ob}
    htmlslice = render_to_string('message/messafe_singleletter.html', context)  # html代码片

    from channels.layers import get_channel_layer
    channel_layer = get_channel_layer()
    kwargs = {
        'type':'receive',
        'message':htmlslice,
        'sender':request.user.username
    }  # kwargs即是前端接受到的event.data

    from asgiref.sync import async_to_sync
    async_to_sync(channel_layer.group_send)(r_user.username+'-message', kwargs)  # 把消息发送到聊天室（频道）
    return JsonResponse({'status':2000,'htmlslice':htmlslice})

segmentfault/apps/notice/views.py
from django.shortcuts import render,reverse,redirect
from django.urls import reverse_lazy
from django.views.generic import ListView
from asgiref.sync import async_to_sync
from django.http.response import JsonResponse
from channels.layers import get_channel_layer
from segmentfault.apps.notice.models import Notice
from segmentfault.apps.users.models import User
from django.contrib.auth.mixins import LoginRequiredMixin

# Create your views here.


class AllNoticeList(LoginRequiredMixin,ListView):
    """
    所有消息
    """
    model = Notice
    template_name = 'notice/notice_list.html'
    context_object_name = 'notice_list'
    paginate_by = 10
    
    def get_queryset(self):
        return self.model.objects.filter(recipient=self.request.user)


class UnReadNoticeList(AllNoticeList):
    """
    未读消息
    """
    def get_queryset(self):
        return super().get_queryset().filter(is_read=False)


def post_notice(sender,recipient,verb,content_object):
    """
    websocket 消息发送函数

    :param sender: 发送者
    :param recipient: 接收者
    :param verb: 类型
    :param content_object:具体实例
    :return:
    """
    Notice.objects.create(
        sender=sender,
        recipient=recipient,
        verb=verb,
        content_object=content_object,  # 手动指定与消息有关的实例，无需通过外键创建
    )

    recipient.has_unread_notice = True  # 该用户有未读消息
    recipient.save()

    channel_layer = get_channel_layer()
    kwargs = {
        'type':'receive',  # 必填字段 必须是receive
        'sender':sender.name,
        'message':'message coming'
    }
    async_to_sync(channel_layer.group_send)('notice-room',kwargs)  # 异步变同步


def notice_light(request):
    """是否有未读通知"""

    if Notice.objects.filter(is_read=False,recipient=request.user):
        return JsonResponse({'status':2000,'msg':True})  # 该用户有未读消息
    return JsonResponse({'status':2000,'msg':False})  # 无未读消息


def mark_read(request):
    """全部标记已读"""
    Notice.read_all(request.user)
    request.user.has_unread_notice = False  # 将有未读消息置为False
    request.user.save()
    return redirect(reverse('notice:all'))

segmentfault/templates/403_csrf.html
{% extends "base.html" %}

{% block title %}Forbidden (403){% endblock %}

{% block content %}
<h1>Forbidden (403)</h1>

<p>CSRF verification failed. Request aborted.</p>
{% endblock content %}

segmentfault/templates/base.html
{% load static i18n compress thumbnail%}<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block title %}segmentfault{% endblock title %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.min.js"></script>
    <![endif]-->

    <link rel="icon" href="{% static 'images/favicons/favicon.ico' %}">

    {% block css %}
    
    <!-- Latest compiled and minified` Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'bootstrap-4.3.1-dist/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/zico.min.css' %}">
    <link href="{% static 'css/project.css' %}" rel="stylesheet">

    <!-- Your stuff: Third-party CSS libraries go here -->
    {% compress css %}
    <!-- This file stores project-specific CSS -->
    

    
    {% endcompress %}
    {% endblock %}

  </head>

  <body>

{#    <div class="mb-1">#}
{#      <nav class="navbar navbar-expand-md navbar-light bg-light">#}
{#        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">#}
{#          <span class="navbar-toggler-icon"></span>#}
{#        </button>#}
{#        <a class="navbar-brand" href="{% url 'home' %}">segmentfault</a>#}
{##}
{#        <div class="collapse navbar-collapse" id="navbarSupportedContent">#}
{#          <ul class="navbar-nav mr-auto">#}
{#            <li class="nav-item active">#}
{#              <a class="nav-link" href="{% url 'users:userhome' %}">首页 <span class="sr-only">(current)</span></a>#}
{#            </li>#}
{#            <li class="nav-item">#}
{#              <a class="nav-link" href="{% url 'qa:new' %}">问答</a>#}
{#            </li>#}
{#            <li class="nav-item">#}
{#              <a class="nav-link" href="{% url 'article:list' %}">文章</a>#}
{#            </li>#}
{#            <li class="nav-item">#}
{#              <a class="nav-link" href="{% url 'circle:list' %}">圈子</a>#}
{#            </li>#}
{#            {% if request.user.is_authenticated %}#}
{#              <li class="nav-item">#}
                {# URL provided by django-allauth/account/urls.py #}
{#                <a class="nav-link" href="{% url 'users:detail' request.user.username  %}">{% trans "My Profile" %}</a>#}
{#              </li>#}
{#              <li class="nav-item">#}
                {# URL provided by django-allauth/account/urls.py #}
{#                <a class="nav-link" href="{% url 'account_logout' %}">{% trans "Sign Out" %}</a>#}
{#              </li>#}
{#            {% else %}#}
{#              <li class="nav-item">#}
                {# URL provided by django-allauth/account/urls.py #}
{#                <a id="sign-up-link" class="nav-link" href="{% url 'account_signup' %}">{% trans "Sign Up" %}</a>#}
{#              </li>#}
{#              <li class="nav-item">#}
                {# URL provided by django-allauth/account/urls.py #}
{#                <a id="log-in-link" class="nav-link" href="{% url 'account_login' %}">{% trans "Sign In" %}</a>#}
{#              </li>#}
{#            {% endif %}#}
{#          </ul>#}
{#        </div>#}
{#      </nav>#}
{#    </div>#}

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container">
            <a class="navbar-brand" href="#">segmentfault</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
              <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'qa:new' %}">问答</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'article:list' %}">文章</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'circle:list' %}">圈子</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'msg:allletter' %}">私信</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'notice:all' %}">
                    <i class="zi {% if request.user.is_authenticated and request.user.has_unread_notice %}zi_bells{% else %}zi_bell{% endif %}" zico="铃铛"></i>
                  </a>
                </li>

                <li></li>
              </ul>
              <form class="form-inline my-2 my-lg-0" method="get" action="{% url 'haystack_search' %}">
                <input class="form-control mr-sm-2" type="search" placeholder="全站搜索" aria-label="Search" name="q">
                <button class="btn btn-outline-secondary my-2 my-sm-0" type="submit"><i class="zi zi_searchBlack" zico="搜索粗黑"></i></button>
              </form>
              <p>&nbsp;&nbsp;&nbsp;</p>



              {% if request.user.is_authenticated %}
                <ul class="navbar-nav mr-auto">
                  <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      {% thumbnail request.user.picture "40x40" crop="center" as im %}
                      <img class="mr-3" src="{{ im.url }}" alt="Generic placeholder image">
                      {% empty %}
                      <img src="{% static 'img/user.png' %}" height="180px" alt="没有头像"/>
                      {% endthumbnail %}
                      {{ request.user }}
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                      <a class="dropdown-item" href="{% url 'users:detail' request.user.username  %}"><i class="zi zi_useralt">  我的主页</i></a>
                      <a class="dropdown-item" href="{% url 'msg:allletter' %}"><i class="zi zi_chat">  私信</i></a>
                      <a class="dropdown-item" href="{% url 'notice:all' %}"><i class="zi zi_bell" zico="铃铛">  消息</i></a>
                      <a class="dropdown-item" href="{% url 'account_logout' %}"><i class="zi zi_signoutalt" zico="出口标志">  注销</i></a>
                    </div>
                  </li>
                </ul>

              {% else %}
                <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                  {# URL provided by django-allauth/account/urls.py #}
                  <a id="sign-up-link" class="nav-link" href="{% url 'account_signup' %}">{% trans "Sign Up" %}</a>
                </li>
                <li class="nav-item">
                  {# URL provided by django-allauth/account/urls.py #}
                  <a id="log-in-link" class="nav-link" href="{% url 'account_login' %}">{% trans "Sign In" %}</a>
                </li>
                </ul>
              {% endif %}


            </div>
      </div>
    </nav>
<p></p>

    <div class="container">


      {% if messages %}
          {% for message in messages %}
              <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}">{{ message }}</div>
          {% endfor %}
      {% endif %}

      {% block content %}
        <p>Use this document as a way to quick start any new project.</p>
      {% endblock content %}

    </div> <!-- /container -->

    {% block modal %}{% endblock modal %}

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="{% static 'js/reconnecting-websocket.js' %}"></script>
    {% block javascript %}
      {% compress js %}
      <!-- Bootstrap JS and its dependencies-->
      <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
      <script src="{% static 'js/popper.min.js' %}"></script>
      <script src="{% static 'bootstrap-4.3.1-dist/js/bootstrap.min.js' %}"></script>
      {% endcompress %}
      <!-- Your stuff: Third-party javascript libraries go here -->
      

      <!-- place project specific Javascript in this file -->




    {% endblock javascript %}
    <script type="text/javascript">
      $.ajaxSetup({
          data: {csrfmiddlewaretoken: '{{ csrf_token }}' },
      });
      const username = '{{ request.user }}'
    </script>
    <script src="{% static 'js/project.js' %}"></script>
  </body>
</html>
 

segmentfault/templates/pagination.html
{% if is_paginated %}
    <nav aria-label="Topics pagination" class="mb-4">
        <ul class="pagination">
            {% if page_obj.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.previous_page_number }}">上一页</a>
                </li>
            {% else %}
                <li class="page-item disabled">
                    <span class="page-link">上一页</span>
                </li>
            {% endif %}

            {% for page_num in paginator.page_range %}
                {% if page_obj.number == page_num %}
                    <li class="page-item active">
                            <span class="page-link">
                                {{ page_num }}
                                <span class="sr-only">(当前页)</span>
                            </span>
                    </li>
                {% elif page_num > page_obj.number|add:'-3' and page_num < page_obj.number|add:'3' %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_num }}">{{ page_num }}</a>
                    </li>
                {% endif %}
            {% endfor %}

            {% if page_obj.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.next_page_number }}">下一页</a>
                </li>
            {% else %}
                <li class="page-item disabled">
                    <span class="page-link">下一页</span>
                </li>
            {% endif %}
        </ul>
    </nav>
{% endif %}

segmentfault/templates/test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>